package com.cc221042.shutterscout

import androidx.room.Entity
import androidx.room.PrimaryKey

// Entity annotation defines the structure of the table in the Room database
@Entity(tableName = "places")
data class Place(
    // Column for storing the title of the place
    val title: String,
    // Column for storing the wanted weather conditions of the place
    val condition: String,
    // Column for storing the image Uri of the place if any
    val imageUri: String,
    // lat and lon position of the image
    val latitude: Double? = null,
    val longitude: Double? = null,
    // Primary key for uniquely identifying each place, auto-generated by Room
    @PrimaryKey(autoGenerate = true) val id: Int = 0
)